# Predefined scores for universities
UNIVERSITY_SCORES = {
    'MIT': 200,
    'Stanford University': 196,
    'Carnegie Mellon University': 195,
    'University of California, Berkeley (UC Berkeley)': 189,
    #'UC Berkeley': 189,
    'University of Washington': 186,
    'University of Illinois Urbana-Champaign': 179,
    'University of Michigan--Ann Arbor': 176,
    'University of California, San Diego (UCSD)': 169,
    'University of Toronto': 166,
    'Harvard University': 159,
    'University of Texas at Austin': 156,
    'Georgia Institute of Technology (Georgia Tech)': 149,
    'University of California, Los Angeles (UCLA)': 146,
    'Cornell University': 138,
    'University of Pennsylvania': 139,
    'Princeton University': 170,
    'California Institute of Technology (Caltech)': 168,
    'University of Cambridge': 165,
    'University of Oxford': 163,
    'National University of Singapore (NUS)': 160,
    'ETH Zurich - Swiss Federal Institute of Technology': 158,
    'Tsinghua University': 155,
    'Peking University': 153,
    'University of Tokyo': 150,
    'Seoul National University': 145,
    'University of British Columbia': 142,
    'University of Melbourne': 140,
    'University of Edinburgh': 138,
    'New York University (NYU)': 135,
    'University of Hong Kong (HKU)': 133,
    'University of Wisconsin--Madison': 130,
    'University of Manchester': 128,
    'University of Queensland': 125,
    'University of Amsterdam': 122,
    'University of Copenhagen': 120,
    'University of Zurich': 118,
    'University of Bristol': 115,
    'McGill University': 112,
    'Duke University': 110,
    'University of California, Santa Barbara (UCSB)': 108,
    'University of Southern California (USC)': 105,
    'KU Leuven': 102,
    'University of Warwick': 100,
    'IIT Delhi': 98,
    'University of Oregon': 95,
    'University of California, Irvine (UCI)': 93,
    'University of California, Davis (UC Davis)': 90,
    'University of Maryland, College Park': 88,
    'University of California, Riverside (UC Riverside)': 85,
    'University of California, San Francisco (UC San Francisco)': 83,
    'University of California, Santa Cruz (UCSC)': 80,
    'University of California, San Diego (UCSD)': 78,
    'IIT Bombay': 76,
    'University of Southampton': 75,
    'Universaite de Montreale': 117
}
